# Generated by Django 6.0.2 on 2026-02-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_studentprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Номер телефону'),
        ),
    ]
